### ISSUE TITLE
View wigs out when switching from a 3D mode to Sky mode

### ISSUE THREAD

**Issue by pkgw** [glue-viz/glue-wwt#50]
To reproduce:

1. Load up a dataset in Glue and view it in WWT in the Sky mode.
2. Switch from Sky mode to Milky Way or Universe mode. Let the view settle.
3. Switch back to Sky mode.

For me, this causes the view to totally wig out, flashing back and forth in a way that could probably cause a seizure. Eventually, however, the view does stabilize.

This does not happen for me in Solar System mode.

I'd guess that when this happens, the camera is flying through 3D space in a reverse of what happens when you navigate from Sky mode to a 3D mode, but some setting is wrong such that the nominal view is flying all over the place.

**Comment by astrofrog** [comment]
This is a web client issue - see https://github.com/WorldWideTelescope/wwt-web-client/issues/199. I'll close this for now since we already have an issue there.
