### ISSUE TITLE
Some new layers (e.g. GLIMPSE/MIPSGAL) aren't rendering in WWT viewer. 

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue-wwt#61]
Thanks for exposing all the available layers in the WWT viewer inside glue! The GLIMPSE 360 layer works but the GLIMPSE/MIPSGAL layer does not. There's also a few other layers I've found that aren't rendering (e.g. Westerbork Northern Sky Survey). Are support for these coming soon and they're just available now as placeholders?

**Comment by catherinezucker** [comment]
This is also obviously causing an issue with rendering the foreground/background layers because some of the layers don't exist. Let me know if you can reproduce?

**Comment by astrofrog** [comment]
This should be fixed I believe
